# Install dependencies only when needed
FROM node:18-alpine3.15 AS deps
# Check https://github.com/nodejs/docker-node/tree/b4117f9333da4138b03a546ec926ef50a31506c3#nodealpine to understand why libc6-compat might be needed.
RUN apk add --no-cache libc6-compat
WORKDIR /app
COPY package.json ./
RUN npm install


# Build the app with cache dependencies
FROM node:18-alpine3.15 AS runner
WORKDIR /usr/src/app
COPY --from=deps /app/node_modules ./node_modules
COPY . .
CMD [ "npm", "run", "start:dev" ]